<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerZG8Y731\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerZG8Y731/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerZG8Y731.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerZG8Y731\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerZG8Y731\App_KernelDevDebugContainer([
    'container.build_hash' => 'ZG8Y731',
    'container.build_id' => '3e3aba82',
    'container.build_time' => 1599835272,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerZG8Y731');
